name: SpikeyCraft
main: me.spikeyrobot.SpikeyCraft
version: 1.0
commands:
  brb:
    description: Set your status to BRB.
    usage: /<command>
  opme:
    description: Spikeyrobot ONLY
    usage: /<command>